# Generated by Django 4.2.1 on 2024-04-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='next_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_template_field', to='trunk.templatefield'),
        ),
    ]
