# Generated by Django 4.2.1 on 2024-04-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0003_alter_templatefield_next_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст шаблона'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.templatefield', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Место поля'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='tag',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.templatefield', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.record', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tag',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='next_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_template_field', to='trunk.template', verbose_name='Следующий шаблон'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Место поля'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tag',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trunk.template', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('B', 'Bool'), ('E', 'E-mail'), ('U', 'URL'), ('C', 'Choices'), ('M', 'Multichoice')], max_length=1, verbose_name='Тип'),
        ),
    ]
